apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: simple-webapp-docker
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'simple-webapp-docker:latest'
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: 'https://github.com/openshift/django-ex.git'
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 'python:3.6'
        namespace: openshift
    type: Source
  triggers:
    - imageChange:
        lastTriggeredImageID: >-
          172.30.1.1:5000/openshift/python@sha256:ac50754646f0d37616515fb30467d8743fb12954260ec36c9ecb5a94499447e0
      type: ImageChange
    - type: ConfigChange
    - generic:
        secret: 46c7d0626bfde7e2
      type: Generic
    - github:
        secret: fbf26c8ab1804f2d
      type: GitHub
